-- Supabase SQL Editor에서 실행하세요. 기존 데이터는 삭제하지 않습니다.
begin;

create table if not exists public.class_settings (
  id boolean primary key default true check(id),
  meal_deadline time not null default '12:00' check(extract(second from meal_deadline)=0),
  updated_at timestamptz not null default now()
);
insert into public.class_settings(id) values(true) on conflict(id) do nothing;

create table if not exists public.seat_statuses (
  seat_number integer primary key check(seat_number between 1 and 30),
  is_unavailable boolean not null default false,
  reason text not null default '' check(length(reason)<=300),
  updated_at timestamptz not null default now(),
  check(not is_unavailable or length(trim(reason))>0)
);
insert into public.seat_statuses(seat_number)
select generate_series(1,30) on conflict(seat_number) do nothing;

create table if not exists public.seat_reports (
  id bigint generated by default as identity primary key,
  seat_number integer not null references public.seat_statuses(seat_number),
  reporter_name text not null check(length(trim(reporter_name)) between 1 and 30),
  reason text not null check(length(trim(reason)) between 1 and 500),
  status text not null default 'open' check(status in('open','resolved')),
  created_at timestamptz not null default now(), resolved_at timestamptz
);

create table if not exists public.meal_group_runs (
  group_date date primary key, result jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.class_settings enable row level security;
alter table public.seat_statuses enable row level security;
alter table public.seat_reports enable row level security;
alter table public.meal_group_runs enable row level security;
revoke all on public.class_settings, public.seat_statuses, public.seat_reports, public.meal_group_runs from public, anon, authenticated;
grant all on public.class_settings, public.seat_statuses, public.seat_reports, public.meal_group_runs to service_role;
grant usage, select on sequence public.seat_reports_id_seq to service_role;

-- 신청 명단은 서버의 관리자 API만 조회합니다. 학생 API는 집계만 반환합니다.
revoke all on public.meal_choices, public.meal_groups from public, anon, authenticated;
grant all on public.meal_choices, public.meal_groups to service_role;
alter table public.meal_groups add column if not exists floor integer;
alter table public.meal_groups add column if not exists floor_group_no integer;
create unique index if not exists meal_groups_date_floor_no_idx
  on public.meal_groups(group_date, floor, floor_group_no);

create or replace function public.generate_meal_groups_for_date(p_group_date date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_floor integer;
  names text[];
  applicant_count integer;
  groups_of_4 integer;
  groups_of_3 integer;
  group_size integer;
  offset_no integer;
  current_floor_group_no integer;
  global_group_no integer := 1;
  members text[];
  result_groups jsonb := '[]'::jsonb;
  floor_results jsonb := '[]'::jsonb;
  result_messages text[] := array[]::text[];
  total_applicants integer := 0;
  total_groups integer := 0;
begin
  if p_group_date is null then
    raise exception '조를 생성할 날짜가 필요합니다.';
  end if;

  perform pg_advisory_xact_lock(hashtext('meal_groups:' || p_group_date::text));
  delete from public.meal_groups where group_date = p_group_date;

  foreach target_floor in array array[10, 20]
  loop
    select array_agg(student_name order by random())
      into names
      from public.meal_choices
     where choice_date = p_group_date
       and floor = target_floor;

    applicant_count := coalesce(array_length(names, 1), 0);
    total_applicants := total_applicants + applicant_count;
    -- 같은 층 신청자가 정확히 5명이면 5명 조 하나로 편성합니다.
    groups_of_4 := case when applicant_count = 5 then 0
      else floor(applicant_count / 4.0)::integer end;

    while applicant_count <> 5 and groups_of_4 >= 0
      and mod(applicant_count - groups_of_4 * 4, 3) <> 0
    loop
      groups_of_4 := groups_of_4 - 1;
    end loop;

    if applicant_count = 0 or groups_of_4 < 0 then
      result_messages := array_append(
        result_messages,
        format('%s층 밥친구 생성 실패 (%s명)', target_floor, applicant_count)
      );
      floor_results := floor_results || jsonb_build_array(jsonb_build_object(
        'floor', target_floor,
        'success', false,
        'applicantCount', applicant_count,
        'groupCount', 0,
        'message', format('%s층 밥친구 생성 실패 (%s명)', target_floor, applicant_count)
      ));
      continue;
    end if;

    groups_of_3 := case when applicant_count = 5 then 0
      else (applicant_count - groups_of_4 * 4) / 3 end;
    offset_no := 1;
    current_floor_group_no := 1;

    for group_size in
      select size from (
        select 5 as size, 1 as sort_no where applicant_count = 5
        union all
        select 4 as size, series_no as sort_no
          from generate_series(1, groups_of_4) as series_values(series_no)
        union all
        select 3 as size, groups_of_4 + series_no as sort_no
          from generate_series(1, groups_of_3) as series_values(series_no)
      ) sizes order by sort_no
    loop
      members := names[offset_no:offset_no + group_size - 1];
      insert into public.meal_groups(
        group_date, group_no, floor, floor_group_no, members
      ) values (
        p_group_date, global_group_no, target_floor, current_floor_group_no, to_jsonb(members)
      );
      result_groups := result_groups || jsonb_build_array(jsonb_build_object(
        'floor', target_floor,
        'floorGroupNo', current_floor_group_no,
        'members', to_jsonb(members)
      ));
      offset_no := offset_no + group_size;
      current_floor_group_no := current_floor_group_no + 1;
      global_group_no := global_group_no + 1;
      total_groups := total_groups + 1;
    end loop;

    result_messages := array_append(
      result_messages,
      format('%s층 %s개 조 생성 완료', target_floor, current_floor_group_no - 1)
    );
    floor_results := floor_results || jsonb_build_array(jsonb_build_object(
      'floor', target_floor,
      'success', true,
      'applicantCount', applicant_count,
      'groupCount', current_floor_group_no - 1,
      'message', format('%s층 %s개 조 생성 완료', target_floor, current_floor_group_no - 1)
    ));
  end loop;

  return jsonb_build_object(
    'ok', total_groups > 0,
    'message', array_to_string(result_messages, ' · '),
    'applicantCount', total_applicants,
    'groupCount', total_groups,
    'groups', result_groups,
    'floorResults', floor_results
  );
end;
$$;


revoke all on function public.generate_meal_groups_for_date(date) from public,anon,authenticated;
grant execute on function public.generate_meal_groups_for_date(date) to service_role;

create or replace function public.submit_meal_friend(
  p_student_name text, p_floor integer, p_cancel boolean default false,
  p_now timestamptz default now()
)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare
  kst timestamp := p_now at time zone 'Asia/Seoul';
  choice_day date := kst::date;
  deadline time;
  had_groups boolean;
  changed_count integer;
  student_name_value text := trim(p_student_name);
begin
  perform pg_advisory_xact_lock(hashtext('meal_groups:' || choice_day::text));
  -- 마감 변경과 신청 요청이 동시에 오더라도 동일한 설정 행을 기준으로 처리합니다.
  select meal_deadline into deadline from public.class_settings where id=true for share;
  if deadline is null then raise exception '밥친구 마감 설정이 없습니다.'; end if;
  if kst::time >= deadline then raise exception '% 이후에는 신청·변경·취소를 할 수 없습니다.', to_char(deadline,'HH24:MI'); end if;
  if p_cancel is null or (not p_cancel and (p_floor is null or p_floor not in(10,20))) then
    raise exception '10층 또는 20층을 선택해주세요.';
  end if;
  if not exists(select 1 from public.students where name=student_name_value and is_active=true) then
    raise exception '등록된 활성 학생 이름을 입력해주세요.';
  end if;
  select exists(select 1 from public.meal_groups where group_date=choice_day) into had_groups;
  if p_cancel then
    delete from public.meal_choices where choice_date=choice_day and student_name=student_name_value;
  else
    insert into public.meal_choices(choice_date,student_name,floor,updated_at)
    values(choice_day,student_name_value,p_floor,p_now)
    on conflict(choice_date,student_name) do update set floor=excluded.floor,updated_at=excluded.updated_at
    where meal_choices.floor is distinct from excluded.floor;
  end if;
  get diagnostics changed_count = row_count;
  if had_groups and changed_count>0 then perform public.generate_meal_groups_for_date(choice_day); end if;
  if changed_count>0 then
    delete from public.meal_group_runs where group_date=choice_day;
  end if;
  return jsonb_build_object('ok',true,'cancelled',p_cancel);
end;
$$;
revoke all on function public.submit_meal_friend(text,integer,boolean,timestamptz) from public,anon,authenticated;
grant execute on function public.submit_meal_friend(text,integer,boolean,timestamptz) to service_role;

create or replace function public.generate_due_meal_groups(p_now timestamptz default now())
returns jsonb language plpgsql security definer set search_path=public
as $$
declare
  kst timestamp := p_now at time zone 'Asia/Seoul';
  day date := kst::date;
  deadline time;
  result jsonb;
begin
  perform pg_advisory_xact_lock(hashtext('meal_groups:' || day::text));
  select meal_deadline into deadline from public.class_settings where id=true for share;
  if deadline is null then raise exception '밥친구 마감 설정이 없습니다.'; end if;
  if extract(isodow from kst)>5 or kst::time<deadline then
    return jsonb_build_object('skipped',true,'reason','마감 전 또는 주말');
  end if;
  if exists(select 1 from public.meal_group_runs where group_date=day) then
    return jsonb_build_object('skipped',true,'reason','이미 자동 편성 완료');
  end if;
  result := public.generate_meal_groups_for_date(day);
  insert into public.meal_group_runs(group_date,result) values(day,result);
  return result;
end;
$$;
revoke all on function public.generate_due_meal_groups(timestamptz) from public,anon,authenticated;
grant execute on function public.generate_due_meal_groups(timestamptz) to service_role;

create or replace function public.set_meal_deadline(p_deadline time)
returns void language plpgsql security definer set search_path=public
as $$
declare
  day date := (now() at time zone 'Asia/Seoul')::date;
  old_deadline time;
begin
  if p_deadline is null or extract(second from p_deadline)<>0 or p_deadline>='24:00'::time then
    raise exception '유효한 마감 시간을 선택해주세요.';
  end if;
  perform pg_advisory_xact_lock(hashtext('meal_groups:' || day::text));
  select meal_deadline into old_deadline from public.class_settings where id=true for update;
  update public.class_settings set meal_deadline=p_deadline,updated_at=now() where id=true;
  if old_deadline is distinct from p_deadline then
    delete from public.meal_group_runs where group_date=day;
  end if;
end;
$$;
revoke all on function public.set_meal_deadline(time) from public,anon,authenticated;
grant execute on function public.set_meal_deadline(time) to service_role;

create or replace function public.check_seating_availability()
returns trigger language plpgsql set search_path=public
as $$
begin
  if exists (
    select 1 from jsonb_object_keys(new.assignment) as seats(seat)
    where seat !~ '^(?:[1-9]|[12][0-9]|30)$'
  ) then raise exception '자리 번호는 1번부터 30번까지만 가능합니다.'; end if;
  if exists (
    select 1 from public.seat_statuses
    where is_unavailable and new.assignment ? seat_number::text
  ) then raise exception '사용 불가 좌석에는 학생을 배치할 수 없습니다.'; end if;
  return new;
end;
$$;
drop trigger if exists check_seating_availability on public.seating_schedules;
create trigger check_seating_availability before insert or update of assignment
on public.seating_schedules for each row execute function public.check_seating_availability();

-- 오래된 공개 신청/취소 함수로 마감을 우회하지 못하게 합니다.
do $$
begin
  if to_regprocedure('public.submit_meal_choice(text,integer)') is not null then
    execute 'revoke all on function public.submit_meal_choice(text,integer) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.cancel_meal_choice(text)') is not null then
    execute 'revoke all on function public.cancel_meal_choice(text) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.generate_today_meal_groups()') is not null then
    execute 'revoke all on function public.generate_today_meal_groups() from public,anon,authenticated';
    execute 'grant execute on function public.generate_today_meal_groups() to service_role';
  end if;
end;
$$;

-- 업데이트 전에 오늘 조를 이미 편성했다면 첫 Cron이 이를 다시 추첨하지 않습니다.
-- 이후 신청 변경·취소 또는 마감 시간 변경 시에는 자동 편성을 다시 준비합니다.
insert into public.meal_group_runs(group_date,result)
select (now() at time zone 'Asia/Seoul')::date, jsonb_build_object('preserved',true)
where exists (
  select 1 from public.meal_groups
  where group_date=(now() at time zone 'Asia/Seoul')::date and floor in(10,20)
)
on conflict(group_date) do nothing;

create or replace function public.get_active_seating()
returns table(effective_date date, assignment jsonb)
language sql
security definer
set search_path = public
as $$
  select effective_date, assignment
  from public.seating_schedules
  where effective_date <= (now() at time zone 'Asia/Seoul')::date + 7
  order by effective_date desc
  limit 1
$$;

grant execute on function public.get_active_seating() to anon, authenticated;

-- 학생이 테이블을 직접 조회해도 아직 공개일이 되지 않은 예약은 보이지 않습니다.
drop policy if exists "public read seating" on public.seating_schedules;
create policy "public read seating"
on public.seating_schedules
for select to anon, authenticated
using (effective_date <= (now() at time zone 'Asia/Seoul')::date + 7);


commit;
