
-- 학생 관리 + 기본 20층 배정 + 메뉴 사진 + 3~4명 점심 조
-- Supabase SQL Editor에서 한 번 실행하세요.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null unique,
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.students(name)
select name
from unnest(array[
  '윤승환','박태준','김호영','강현규','최민재','이다빈','유진아','박민지','김휘서',
  '김보명','송민철','방송현','손희상','유지예','노진우','유진혁','정희진','태현식',
  '정준','박연서','문경준','임홍철','조민석','이민석','조정빈','김가영','정다운'
]) as name
on conflict(name) do nothing;

alter table public.daily_menus
  add column if not exists menu_20_items jsonb not null default '[]'::jsonb;

alter table public.students enable row level security;

drop policy if exists "public read active students" on public.students;
create policy "public read active students"
on public.students
for select
to anon, authenticated
using (is_active = true);

-- 이름은 학생 테이블에 등록된 활성 학생만 허용
create or replace function public.submit_meal_choice(
  p_student_name text,
  p_floor integer
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  kst timestamp := now() at time zone 'Asia/Seoul';
  d date := kst::date;
begin
  if extract(hour from kst) >= 11 then
    raise exception '오전 11시 이후에는 선택할 수 없습니다.';
  end if;

  if p_floor not in (10,20) then
    raise exception '10층 또는 20층만 선택할 수 있습니다.';
  end if;

  if not exists (
    select 1
    from public.students
    where name = trim(p_student_name)
      and is_active = true
  ) then
    raise exception '등록된 학생 이름이 아닙니다.';
  end if;

  insert into public.meal_choices(choice_date,student_name,floor)
  values(d,trim(p_student_name),p_floor)
  on conflict(choice_date,student_name)
  do update set
    floor=excluded.floor,
    updated_at=now();
end;
$$;

grant execute on function public.submit_meal_choice(text,integer)
to anon, authenticated;

-- 아무 선택도 하지 않은 활성 학생은 20층으로 간주합니다.
-- 명시적으로 10층을 선택한 학생만 20층 조에서 제외합니다.
-- 조는 가능한 경우 3명 또는 4명으로 구성합니다.
create or replace function public.generate_today_meal_groups()
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  d date := (now() at time zone 'Asia/Seoul')::date;
  names text[];
  n integer;
  index_value integer := 1;
  group_number integer := 1;
  groups_of_3 integer := 0;
  groups_of_4 integer := 0;
  current_group_size integer;
  group_members text[];
  loop_number integer;
begin
  delete from public.meal_groups where group_date=d;

  select array_agg(s.name order by random())
  into names
  from public.students s
  left join public.meal_choices c
    on c.choice_date=d
   and c.student_name=s.name
  where s.is_active=true
    and coalesce(c.floor,20)=20;

  n := coalesce(array_length(names,1),0);

  if n=0 then
    return;
  end if;

  -- 1, 2명은 작은 조로 생성하여 누락을 막음
  if n <= 2 then
    insert into public.meal_groups(group_date,group_no,members)
    values(d,1,to_jsonb(names));
    return;
  end if;

  -- 5명은 3+2로 구성 (3/4명만으로는 불가능)
  if n=5 then
    insert into public.meal_groups(group_date,group_no,members)
    values(d,1,to_jsonb(names[1:3]));

    insert into public.meal_groups(group_date,group_no,members)
    values(d,2,to_jsonb(names[4:5]));
    return;
  end if;

  groups_of_4 := n / 4;

  while groups_of_4 >= 0 loop
    if mod(n - groups_of_4 * 4, 3)=0 then
      groups_of_3 := (n - groups_of_4 * 4) / 3;
      exit;
    end if;
    groups_of_4 := groups_of_4 - 1;
  end loop;

  if groups_of_4 > 0 then
    for loop_number in 1..groups_of_4 loop
      current_group_size := 4;
      group_members := names[index_value:index_value+current_group_size-1];

      insert into public.meal_groups(group_date,group_no,members)
      values(d,group_number,to_jsonb(group_members));

      index_value := index_value + current_group_size;
      group_number := group_number + 1;
    end loop;
  end if;

  if groups_of_3 > 0 then
    for loop_number in 1..groups_of_3 loop
      current_group_size := 3;
      group_members := names[index_value:index_value+current_group_size-1];

      insert into public.meal_groups(group_date,group_no,members)
      values(d,group_number,to_jsonb(group_members));

      index_value := index_value + current_group_size;
      group_number := group_number + 1;
    end loop;
  end if;
end;
$$;

-- 서버 함수(service role)가 실행하지만 수동 RPC 호환도 유지
grant execute on function public.generate_today_meal_groups()
to authenticated;

-- 학생 화면용 공개 조회
drop policy if exists "public read menus" on public.daily_menus;
create policy "public read menus"
on public.daily_menus for select
to anon, authenticated
using(true);

drop policy if exists "public read groups" on public.meal_groups;
create policy "public read groups"
on public.meal_groups for select
to anon, authenticated
using(true);
