-- 학생 관리 스키마 보강
-- 실행 후 meal_friend_security_and_integrity_patch.sql도 실행하세요.
create table if not exists public.students (
 id bigint generated by default as identity primary key,
 name text not null unique, note text, is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.students(name)
select name from unnest(array[
 '윤승환','박태준','김호영','강현규','최민재','이다빈','유진아','박민지','김휘서',
 '김보명','송민철','방송현','손희상','유지예','노진우','유진혁','정희진','태현식',
 '정준','박연서','문경준','임홍철','조민석','이민석','조정빈','김가영','정다운'
]) as name on conflict(name) do nothing;
alter table public.daily_menus add column if not exists menu_20_items jsonb not null default '[]'::jsonb;
alter table public.students enable row level security;
drop policy if exists "public read active students" on public.students;
create policy "public read active students" on public.students
 for select to anon,authenticated using(is_active=true);
-- 학생 신청과 관리자 변경은 검증된 서버 API에서 service role로 수행합니다.
-- 이전 공개 RPC가 존재하는 설치에서는 최신 보안 패치가 실행 권한을 제거합니다.
drop policy if exists "public read menus" on public.daily_menus;
create policy "public read menus" on public.daily_menus for select to anon,authenticated using(true);
drop policy if exists "public read groups" on public.meal_groups;
create policy "public read groups" on public.meal_groups for select to anon,authenticated using(true);
