-- 밥 친구: 신청자만 3~4명 랜덤 매칭
-- Supabase > SQL Editor에서 한 번 실행하세요.

create table if not exists public.meal_group_applications (
  id bigint generated by default as identity primary key,
  application_date date not null,
  student_name text not null,
  created_at timestamptz not null default now(),
  unique (application_date, student_name)
);

create index if not exists idx_meal_group_applications_date
  on public.meal_group_applications(application_date);

alter table public.meal_group_applications enable row level security;

-- 학생 화면에서는 직접 테이블을 수정하지 않고 아래 SECURITY DEFINER 함수만 사용합니다.

create or replace function public.submit_meal_group_application(
  p_student_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(p_student_name);
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_hour integer := extract(hour from (now() at time zone 'Asia/Seoul'));
begin
  if v_hour >= 11 then
    raise exception '밥 친구 신청은 오전 11시까지 가능합니다.';
  end if;

  if v_name = '' then
    raise exception '이름을 입력하세요.';
  end if;

  if not exists (
    select 1
    from public.students
    where name = v_name
      and is_active = true
  ) then
    raise exception '등록된 활성 학생이 아닙니다.';
  end if;

  insert into public.meal_group_applications (
    application_date,
    student_name
  )
  values (
    v_today,
    v_name
  )
  on conflict (application_date, student_name)
  do nothing;
end;
$$;

create or replace function public.cancel_meal_group_application(
  p_student_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(p_student_name);
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_hour integer := extract(hour from (now() at time zone 'Asia/Seoul'));
begin
  if v_hour >= 11 then
    raise exception '밥 친구 신청 취소는 오전 11시까지 가능합니다.';
  end if;

  delete from public.meal_group_applications
  where application_date = v_today
    and student_name = v_name;
end;
$$;

grant execute on function public.submit_meal_group_application(text) to anon, authenticated;
grant execute on function public.cancel_meal_group_application(text) to anon, authenticated;

-- 기존 자동 전원 매칭 RPC가 남아 있어도 더 이상 관리자 화면에서는 호출하지 않습니다.
-- Vercel Cron 등에서 generate_today_meal_groups()를 직접 호출하고 있다면 그 호출도 제거해야 합니다.
