-- 이 파일의 별도 신청 테이블 방식은 현재 앱에서 사용하지 않습니다.
-- 현재 신청은 public.meal_choices에 0(혼자 먹기), 10, 20으로 저장되며,
-- 행이 없는 활성 학생만 미신청으로 표시됩니다.
-- 최신 구조는 supabase_schema.sql과 meal_friend_security_and_integrity_patch.sql을 사용하세요.
