
create extension if not exists pg_cron;

create table if not exists public.seating_schedules(
 id bigint generated by default as identity primary key,
 effective_date date not null unique,
 assignment jsonb not null,
 created_at timestamptz not null default now()
);
create table if not exists public.daily_menus(
 menu_date date primary key,
 menu_10 text, menu_20 text,
 updated_at timestamptz not null default now()
);
create table if not exists public.meal_choices(
 choice_date date not null,
 student_name text not null,
 floor integer not null check(floor in(10,20)),
 updated_at timestamptz not null default now(),
 primary key(choice_date,student_name)
);
create table if not exists public.meal_groups(
 group_date date not null,
 group_no integer not null,
 members jsonb not null,
 created_at timestamptz not null default now(),
 primary key(group_date,group_no)
);

alter table public.seating_schedules enable row level security;
alter table public.daily_menus enable row level security;
alter table public.meal_choices enable row level security;
alter table public.meal_groups enable row level security;

create or replace function public.get_active_seating()
returns table(effective_date date,assignment jsonb)
language sql security definer set search_path=public
as $$select effective_date,assignment from public.seating_schedules
where effective_date <= (now() at time zone 'Asia/Seoul')::date
order by effective_date desc limit 1$$;
grant execute on function public.get_active_seating() to anon,authenticated;

create or replace function public.submit_meal_choice(p_student_name text,p_floor integer)
returns void language plpgsql security definer set search_path=public
as $$
declare kst timestamp:=now() at time zone 'Asia/Seoul'; d date:=kst::date;
begin
 if extract(hour from kst)>=11 then raise exception '오전 11시 이후에는 선택할 수 없습니다.'; end if;
 if p_floor not in(10,20) then raise exception '10층 또는 20층만 선택할 수 있습니다.'; end if;
 insert into public.meal_choices(choice_date,student_name,floor)
 values(d,p_student_name,p_floor)
 on conflict(choice_date,student_name)
 do update set floor=excluded.floor,updated_at=now();
end$$;
grant execute on function public.submit_meal_choice(text,integer) to anon,authenticated;

create or replace function public.generate_today_meal_groups()
returns void language plpgsql security definer set search_path=public
as $$
declare d date:=(now() at time zone 'Asia/Seoul')::date;
 names text[]; n int; i int:=1; g int:=1; members text[];
begin
 delete from public.meal_groups where group_date=d;
 select array_agg(student_name order by random()) into names
 from public.meal_choices where choice_date=d and floor=20;
 n:=coalesce(array_length(names,1),0);
 if n=0 then return; end if;
 if mod(n,2)=1 and n>=3 then
   members:=array[names[1],names[2],names[3]];
   insert into public.meal_groups values(d,g,to_jsonb(members),now());
   i:=4; g:=2;
 end if;
 while i<=n loop
   if i=n then
     members:=array[names[i]];
   else
     members:=array[names[i],names[i+1]];
   end if;
   insert into public.meal_groups values(d,g,to_jsonb(members),now());
   i:=i+2; g:=g+1;
 end loop;
end$$;
grant execute on function public.generate_today_meal_groups() to authenticated;

create policy "public read seating" on public.seating_schedules for select to anon,authenticated using(true);
create policy "public read menus" on public.daily_menus for select to anon,authenticated using(true);
create policy "public read groups" on public.meal_groups for select to anon,authenticated using(true);
create policy "admin seating" on public.seating_schedules for all to authenticated using(true) with check(true);
create policy "admin menus" on public.daily_menus for all to authenticated using(true) with check(true);
create policy "admin choices" on public.meal_choices for select to authenticated using(true);
create policy "admin groups" on public.meal_groups for all to authenticated using(true) with check(true);

select cron.unschedule(jobid) from cron.job where jobname='generate-daily-20f-groups';
select cron.schedule(
 'generate-daily-20f-groups',
 '0 2 * * 1-5',
 $$select public.generate_today_meal_groups();$$
);
