-- 기본 Supabase 스키마
-- 실행 후 meal_friend_security_and_integrity_patch.sql도 실행하세요.
create table if not exists public.seating_schedules(
 id bigint generated by default as identity primary key,
 effective_date date not null unique, assignment jsonb not null,
 created_at timestamptz not null default now()
);
create table if not exists public.daily_menus(
 menu_date date primary key, menu_10 text, menu_20 text,
 menu_20_items jsonb not null default '[]'::jsonb,
 updated_at timestamptz not null default now()
);
create table if not exists public.meal_choices(
 choice_date date not null, student_name text not null,
 floor integer not null check(floor in(0,10,20)),
 updated_at timestamptz not null default now(),
 primary key(choice_date,student_name)
);
create table if not exists public.meal_groups(
 group_date date not null, group_no integer not null,
 floor integer not null check(floor in(10,20)), floor_group_no integer not null,
 members jsonb not null, created_at timestamptz not null default now(),
 primary key(group_date,group_no), unique(group_date,floor,floor_group_no)
);
alter table public.seating_schedules enable row level security;
alter table public.daily_menus enable row level security;
alter table public.meal_choices enable row level security;
alter table public.meal_groups enable row level security;
create or replace function public.get_active_seating()
returns table(effective_date date,assignment jsonb)
language sql security definer set search_path=public
as $$select effective_date,assignment from public.seating_schedules
where effective_date <= (now() at time zone 'Asia/Seoul')::date + 7
order by effective_date desc limit 1$$;
grant execute on function public.get_active_seating() to anon,authenticated;
drop policy if exists "public read seating" on public.seating_schedules;
create policy "public read seating" on public.seating_schedules for select to anon,authenticated
using(effective_date <= (now() at time zone 'Asia/Seoul')::date + 7);
drop policy if exists "public read menus" on public.daily_menus;
create policy "public read menus" on public.daily_menus for select to anon,authenticated using(true);
drop policy if exists "public read groups" on public.meal_groups;
create policy "public read groups" on public.meal_groups for select to anon,authenticated using(true);
-- 쓰기 작업은 service role을 사용하는 서버 API에서만 수행합니다.
