import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { test, before, after } from "node:test";
import vm from "node:vm";
import { PGlite } from "@electric-sql/pglite";
import { drawSeating, SEAT_NUMBERS, validateAssignment } from "../shared/classroom.js";
import { getClassSettings, isMealOpen, kstClock, validDeadline, mealSummary } from "../api/_class-settings.js";
import { errorMessage } from "../api/_errors.js";

let db;
before(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create table students(name text primary key, is_active boolean default true);
    create table meal_choices(choice_date date,student_name text,floor integer,updated_at timestamptz default now(),primary key(choice_date,student_name));
    create table meal_groups(group_date date,group_no integer,members jsonb,created_at timestamptz default now(),primary key(group_date,group_no));
    create table seating_schedules(id bigint generated by default as identity,effective_date date unique,assignment jsonb);
    insert into students select 'test_'||i,true from generate_series(1,100) i;
    insert into students values('inactive',false);
    insert into meal_groups(group_date,group_no,members)values('2026-01-01',1,'["historic"]');`);
  const migration = await readFile(new URL("../class_management_update.sql", import.meta.url), "utf8");
  await db.exec(migration);
  await db.exec(migration);
});
after(async () => { await db?.close(); });

test("actual PostgreSQL migration preserves history and creates 5 + 13 members without floor errors", async () => {
  for (const [floor, count, offset] of [[10,5,0],[20,13,5]]) {
    for (let i=1;i<=count;i++) await db.query("insert into meal_choices values($1,$2,$3,now())", ["2026-10-06",`test_${i+offset}`,floor]);
  }
  const { rows } = await db.query("select generate_meal_groups_for_date('2026-10-06') as result");
  assert.equal(rows[0].result.ok,true);
  const groups=(await db.query("select floor,jsonb_array_length(members) as size,members from meal_groups where group_date='2026-10-06' order by group_no")).rows;
  assert.deepEqual(groups.filter(g=>g.floor===10).map(g=>g.size),[5]);
  assert.deepEqual(groups.filter(g=>g.floor===20).map(g=>g.size),[4,3,3,3]);
  assert.equal(new Set(groups.flatMap(g=>g.members)).size,18);
  assert.equal((await db.query("select count(*)::int as count from meal_groups where group_date='2026-01-01'")).rows[0].count,1);
});

test("cancel before noon removes only today's application and updates an already generated five-member group",async()=>{
  await db.query("insert into meal_choices values('2026-10-05','test_1',10,now())");
  await db.query("select submit_meal_friend('test_1',null,true,'2026-10-06 11:59:59+09')");
  assert.equal((await db.query("select count(*)::int as count from meal_choices where choice_date='2026-10-06' and student_name='test_1'")).rows[0].count,0);
  assert.equal((await db.query("select count(*)::int as count from meal_choices where choice_date='2026-10-05' and student_name='test_1'")).rows[0].count,1);
  const groups=(await db.query("select members from meal_groups where group_date='2026-10-06' and floor=10")).rows;
  assert.equal(groups.length,1);assert.equal(groups[0].members.length,4);assert.ok(!groups[0].members.includes('test_1'));
  const beforeRepeat=(await db.query("select members from meal_groups where group_date='2026-10-06' order by group_no")).rows;
  await db.query("select submit_meal_friend('test_1',null,true,'2026-10-06 11:59:59+09')");
  assert.deepEqual((await db.query("select members from meal_groups where group_date='2026-10-06' order by group_no")).rows,beforeRepeat);
  await db.query("select submit_meal_friend('test_1',10,false,'2026-10-06 11:59:59+09')");
  assert.equal((await db.query("select jsonb_array_length(members) as size from meal_groups where group_date='2026-10-06' and floor=10")).rows[0].size,5);
});

test("database rejects application, change and cancellation exactly at the cutoff and rejects solo/inactive users",async()=>{
  for(const cancel of [false,true]) await assert.rejects(db.query("select submit_meal_friend('test_1',20,$1,'2026-10-06 12:00:00+09')",[cancel]), /신청·변경·취소/);
  await assert.rejects(db.query("select submit_meal_friend('test_1',0,false,'2026-10-06 11:00+09')"), /10층 또는 20층/);
  await assert.rejects(db.query("select submit_meal_friend('inactive',10,false,'2026-10-06 11:00+09')"), /활성 학생/);
  await db.query("update class_settings set meal_deadline='12:30'");
  await db.query("select submit_meal_friend('test_1',20,false,'2026-10-06 12:29:59+09')");
  await assert.rejects(db.query("select submit_meal_friend('test_1',null,true,'2026-10-06 12:30:00+09')"), /12:30/);
  await db.query("update class_settings set meal_deadline='12:00'");
});

test("scheduled generation waits for the configured minute and runs once on weekdays",async()=>{
  await db.query("update class_settings set meal_deadline='12:30'");
  for(let i=1;i<=5;i++)await db.query("insert into meal_choices values('2026-10-08',$1,10,now())",[`test_${i}`]);
  const call=async time=>(await db.query("select generate_due_meal_groups($1) as result",[time])).rows[0].result;
  assert.equal((await call('2026-10-08 12:29:59+09')).skipped,true);
  assert.equal((await call('2026-10-08 12:30:00+09')).groupCount,1);
  const original=(await db.query("select members from meal_groups where group_date='2026-10-08'")).rows;
  assert.equal((await call('2026-10-08 12:31+09')).skipped,true);
  assert.deepEqual((await db.query("select members from meal_groups where group_date='2026-10-08'")).rows,original);
  assert.equal((await call('2026-10-10 13:00+09')).skipped,true);
  await db.query("update class_settings set meal_deadline='12:00'");
});

test("changing deadline rearms today's automatic job but saving the same time does not",async()=>{
  const day=(await db.query("select (now() at time zone 'Asia/Seoul')::date::text as day")).rows[0].day;
  await db.query("insert into meal_group_runs values($1,'{}',now()) on conflict(group_date)do nothing",[day]);
  await db.query("select set_meal_deadline('13:10')");
  assert.equal((await db.query("select count(*)::int as count from meal_group_runs where group_date=$1",[day])).rows[0].count,0);
  await db.query("insert into meal_group_runs values($1,'{}',now())",[day]);
  await db.query("select set_meal_deadline('13:10')");
  assert.equal((await db.query("select count(*)::int as count from meal_group_runs where group_date=$1",[day])).rows[0].count,1);
});

test("database and server validation reject unavailable seats; seat one is available",async()=>{
  await db.query("update seat_statuses set is_unavailable=true,reason='고장' where seat_number=2");
  await assert.rejects(db.query("insert into seating_schedules(effective_date,assignment)values('2026-10-20','{\"2\":\"test_1\"}')"),/사용 불가/);
  await db.query("insert into seating_schedules(effective_date,assignment)values('2026-10-20','{\"1\":\"test_1\"}')");
  const statuses=[{seat_number:2,is_unavailable:true}];
  assert.equal(validateAssignment({1:'a'},['a'],statuses),'');
  assert.notEqual(validateAssignment({2:'a'},['a'],statuses),'');
  assert.notEqual(validateAssignment({1:'a',3:'a'},['a'],statuses),'');
  assert.notEqual(validateAssignment({1:'a'},['a','b'],statuses),'');
});

test("students cannot directly read application lists or reports, or call private mutation RPCs",async()=>{
  await db.exec('set role anon');
  try{
    for(const table of ['meal_choices','meal_groups','seat_reports','class_settings']) await assert.rejects(db.query(`select * from ${table}`), error=>error.code==='42501');
    await assert.rejects(db.query("select submit_meal_friend('test_1',10,false)"),error=>error.code==='42501');
  }finally{await db.exec('reset role')}
});

test("random drawing includes every available seat, excludes broken seats, and shuffles people",()=>{
  let seed=12345;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32};
  const observed=new Set(),locations=new Set();
  for(let i=0;i<400;i++){
    const result=drawSeating(['a','b','c'],[2,30],random);
    assert.equal(Object.keys(result).length,3);assert.equal(new Set(Object.values(result)).size,3);assert.ok(!result[2]&&!result[30]);
    Object.keys(result).forEach(seat=>observed.add(Number(seat)));locations.add(Object.entries(result).find(([,name])=>name==='a')[0]);
  }
  assert.deepEqual([...observed].sort((a,b)=>a-b),SEAT_NUMBERS.filter(seat=>![2,30].includes(seat)));
  assert.ok(locations.size>20);assert.throws(()=>drawSeating(Array(31).fill('a').map((value,i)=>value+i)),/사용/);
});

test("KST deadline minute boundary and public count summary never expose an application name",()=>{
  assert.equal(kstClock(Date.parse('2026-10-06T02:59:59Z')).minutes,719);
  assert.equal(isMealOpen('12:00',Date.parse('2026-10-06T02:59:59Z')),true);
  assert.equal(isMealOpen('12:00',Date.parse('2026-10-06T03:00:00Z')),false);
  assert.equal(validDeadline('23:59'),true);assert.equal(validDeadline('24:00'),false);assert.equal(validDeadline('12:60'),false);
  const summary=mealSummary([{name:'a'},{name:'b'},{name:'c'}],[{student_name:'a',floor:10},{student_name:'b',floor:0},{student_name:'inactive',floor:20}]);
  assert.deepEqual(summary,[{floor:10,count:1},{floor:20,count:0},{floor:null,count:2}]);
  assert.ok(!JSON.stringify(summary).includes('student_name'));
});

test("student API sends only counts for applications and calls cancellation RPC; new admin actions require authentication",async()=>{
  const datasets={class_settings:[{meal_deadline:'12:00:00'}],students:[{name:'a'},{name:'b'}],meal_choices:[{student_name:'a',floor:10}],meal_groups:[]};
  const rpcCalls=[];
  const client={from(table){const data=datasets[table]??[];return{select(){return this},eq(){return this},order(){return this},single:async()=>({data:data[0],error:null}),then(resolve,reject){return Promise.resolve({data,error:null}).then(resolve,reject)}}},rpc:async(name,args)=>{rpcCalls.push({name,args});return{error:null}}};
  async function handler(file,extra={}){
    const source=(await readFile(new URL(`../api/${file}`,import.meta.url),'utf8')).replace(/import[\s\S]*?from\s+"[^"]+";/g,'').replace('export default async function handler','async function handler');
    const context=vm.createContext({process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>client,getClassSettings,kstClock,isMealOpen:()=>true,mealSummary,errorMessage,isAdminRequest:()=>false,console:{error(){}},...extra});vm.runInContext(source,context);return context.handler;
  }
  async function call(fn,method,body){let result;await fn({method,body},{setHeader(){},status(code){this.code=code;return this},json(body){result={code:this.code,body};return result}});return result}
  const student=await handler('meal-friends.js');
  const publicData=await call(student,'GET');assert.equal(publicData.code,200);assert.equal(publicData.body.applications,undefined);assert.equal(publicData.body.counts.length,3);
  assert.equal((await call(student,'POST',{studentName:'a',action:'cancel'})).code,200);assert.equal(rpcCalls[0].args.p_cancel,true);assert.equal(rpcCalls[0].args.p_floor,null);
  assert.equal((await call(student,'POST',{studentName:'a',choice:'solo'})).code,400);
  const admin=await handler('admin.js');
  for(const action of ['list_choices','set_seat_status','list_seat_reports','save_meal_deadline']) assert.equal((await call(admin,'POST',{action})).code,401);
});

test("embedded scripts parse and today's group card precedes the application form",async()=>{
  for(const file of ['index.html','admin.html']){
    const html=await readFile(new URL(`../${file}`,import.meta.url),'utf8');
    for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1].replace(/^import .*;$/gm,''));
    assert.ok(!html.includes('혼자 먹기'));
  }
  const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
  assert.ok(html.indexOf('id="friendGroups"')<html.indexOf('id="friendStudentName"'));
  assert.ok(html.includes('id="cancelFriendChoice"'));
});
